
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class NumericLimitCategory : Singleton<NumericLimitCategory>, ISingletonAwake
    {
        private readonly Dictionary<int, NumericLimitConfig> _dataMap;
        private readonly List<NumericLimitConfig> _dataList;
        
        public NumericLimitCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, NumericLimitConfig>();
            _dataList = new List<NumericLimitConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                NumericLimitConfig _v;
                _v = global::ET.NumericLimitConfig.DeserializeNumericLimitConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
        }
        public void Awake()
        {
            
        }

        public Dictionary<int, NumericLimitConfig> GetAll() => _dataMap;
        public Dictionary<int, NumericLimitConfig> DataMap => _dataMap;
        public List<NumericLimitConfig> DataList => _dataList;

        public NumericLimitConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public NumericLimitConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            Log.Instance.Error($"No Found {this.GetType()} {key}");
            return default;
        }

        public bool TryGet(int key, out NumericLimitConfig value)
        {
            return _dataMap.TryGetValue(key, out value);
        }

    }
}


