
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum NumericType
    {
        Level = 100001,
        Exp = 100002,
        Hp = 200001,
        MaxHp = 200002,
        MaxHp1 = 2000021,
        MaxHp2 = 2000022,
        MaxHp3 = 2000023,
        MaxHp4 = 2000024,
        MaxHp5 = 2000025,
        MaxHp6 = 2000026,
        Speed = 200003,
        Speed1 = 2000031,
        Speed2 = 2000032,
        Speed3 = 2000033,
        Speed4 = 2000034,
        Speed5 = 2000035,
        Speed6 = 2000036,
    }

} 

