
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericAffectConfig : Luban.BeanBase
    {
        public NumericAffectConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); Affects = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Affects[__index0] = __e0;}}

        }

        public static NumericAffectConfig DeserializeNumericAffectConfig(ByteBuf _buf)
        {
            return new NumericAffectConfig(_buf);
        }

        public readonly int Id;
        public readonly int[] Affects;
    
        public const int __ID__ = 1951886916;
        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Affects:" + Luban.StringUtil.CollectionToString(Affects) + ","
            + "}";
        }
    }
}


