
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class NumericLimitConfig : Luban.BeanBase
    {
        public NumericLimitConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Min = _buf.ReadLong();
            Max = _buf.ReadLong();

        }

        public static NumericLimitConfig DeserializeNumericLimitConfig(ByteBuf _buf)
        {
            return new NumericLimitConfig(_buf);
        }

        public readonly int Id;
        public readonly long Min;
        public readonly long Max;
    
        public const int __ID__ = 913346992;
        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Min:" + Min + ","
            + "Max:" + Max + ","
            + "}";
        }
    }
}


