//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Numerics;
using System.Runtime.InteropServices;

namespace ET.Client;

[StructLayout(LayoutKind.Sequential)]
public partial struct Shading_MUniform
{
    public Matrix4x4 model;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct Shading_VPUniform
{
    public Matrix4x4 view;
    public Matrix4x4 projection;
}


[StructLayout(LayoutKind.Sequential)]
public partial struct Shadow_MUniform
{
    public Matrix4x4 model;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct Shadow_VPUniform
{
    public Matrix4x4 view;
    public Matrix4x4 projection;
}


[StructLayout(LayoutKind.Sequential)]
public partial struct Shading_LightUniform
{
    public Matrix4x4 view;
    public Matrix4x4 projection;
    public Vector3 dir;
    public float intensity;
    public Vector4 color;
}


