//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Numerics;
using System.Runtime.InteropServices;

namespace ET.Client;

[StructLayout(LayoutKind.Sequential)]
public partial struct Shading_MUniform
{
    public Matrix4x4 model;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct Shading_VPUniform
{
    public Matrix4x4 view;
    public Matrix4x4 projection;
}


[StructLayout(LayoutKind.Sequential)]
public partial struct Shadow_MUniform
{
    public Matrix4x4 model;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct Shadow_VPUniform
{
    public Matrix4x4 view;
    public Matrix4x4 projection;
}


[StructLayout(LayoutKind.Sequential)]
public partial struct PostProcess_CameraUniform
{
    public Matrix4x4 view;
    public Matrix4x4 projection;
    public Vector4 worldPos;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct PostProcess_LightUniform
{
    public Matrix4x4 view;
    public Matrix4x4 projection;
    public Vector3 dir;
    public float intensity;
    public Vector4 color;
    public Vector4 worldPos;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct PostProcess_AtmosParamsUniform
{
    public float planetRadius;
    public float topRadius;
    public float rayleighScaleH;
    public float mieScaleH;
    public Vector3 betaRayleigh;
    public float padding;
    public Vector3 betaMie;
    public float mieG;
}


[StructLayout(LayoutKind.Sequential)]
public partial struct Shading_LightUniform
{
    public Matrix4x4 view;
    public Matrix4x4 projection;
    public Vector3 dir;
    public float intensity;
    public Vector4 color;
    public Vector4 worldPos;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct Shading_CameraUniform
{
    public Matrix4x4 view;
    public Matrix4x4 projection;
    public Vector4 worldPos;
}


