//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Numerics;
using Veldrid;

namespace ET.Client;

public partial struct PostProcessVertex
{
    public Vector2 position;
    public Vector3 dir;

    public static VertexLayoutDescription GetLayout()
    {
        return new VertexLayoutDescription(
            new VertexElementDescription("position", VertexElementSemantic.TextureCoordinate, VertexElementFormat.Float2),
            new VertexElementDescription("dir", VertexElementSemantic.TextureCoordinate, VertexElementFormat.Float3)
        );
    }
}

public partial struct ShadingVertex
{
    public Vector3 position;
    public Vector2 uv;
    public Vector3 normal;

    public static VertexLayoutDescription GetLayout()
    {
        return new VertexLayoutDescription(
            new VertexElementDescription("position", VertexElementSemantic.TextureCoordinate, VertexElementFormat.Float3),
            new VertexElementDescription("uv", VertexElementSemantic.TextureCoordinate, VertexElementFormat.Float2),
            new VertexElementDescription("normal", VertexElementSemantic.TextureCoordinate, VertexElementFormat.Float3)
        );
    }
}

public partial struct ShadowVertex
{
    public Vector3 position;

    public static VertexLayoutDescription GetLayout()
    {
        return new VertexLayoutDescription(
            new VertexElementDescription("position", VertexElementSemantic.TextureCoordinate, VertexElementFormat.Float3)
        );
    }
}

