//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ET;


[Invoke(429501024667298)]
public class NumericAffectHandler_429501024667298 : AInvokeHandler<NumericAffect, long>
{
    /*
    只要等级变化
    正常肯定是升级
    就直接修改经验值
    */
    public override long Handle(NumericAffect A)
    {
        return 0;
    }
}

[Invoke(859002049334593)]
public class NumericAffectHandler_859002049334593 : AInvokeHandler<NumericAffect, long>
{
    /*
    当前最大血量改变时
    如果当前血量>最大血量
    则当前血是修改为最大血量
    */
    public override long Handle(NumericAffect A)
    {
        if(A.AV > A.N)
        {
            return A.N;
        }
        return A.AV;
    }
}

[Invoke(859002051134623)]
public class NumericAffectHandler_859002051134623 : AInvokeHandler<NumericAffect, long>
{
    /*
    案例 移动速度额外增加
    最大血量越高移动速度越快 反之
    */
    public override long Handle(NumericAffect A)
    {
        return A.AV + (A.N - A.O) * 2;
    }
}

